spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    virtual-host: /
    username: wubiqin
    password: 123456
    publisher-confirms: true #支持发布确认
    publisher-returns: true #支持发布返回
    listener:
      simple:
        acknowledge-mode: manual #手动确认
        concurrency: 1 #最少消费者数量
        max-concurrency: 10 #最多消费者数量
        retry:
          enabled: true #支持重试


  chat.zk.address: 127.0.0.1:2181
  chat.zk.timeout: 5000

  chat.redis.address: 127.0.0.1
  chat.redis.port: 6379
  chat.redis.timeout: 5000

  chat.mq.directExchange: directExchange
  chat.mq.directQueue: directQueue
  chat.mq.fanoutExchange: fanoutExchange
  chat.mq.directRoutingKey: directRoutingKey
  chat.mq.fanoutQueue1: fanoutQueue1
  chat.mq.fanoutQueue2: fanoutQueue2



